In [6]:
import numpy as np
import pandas as pd

In [ ]:
#numpy arrays are faster than lists and can be used for mathematical operations (vectorized operations)
array = np.array(1) #zero-dimensional array

#one and two-dimensional arrays can be created using lists of lists
array1 = np.array(['A', 'B', 'C', 'D', 'E']) #one-dimensional array
array2 = np.array([['A', 'B'],
                   ['C', 'D'], 
                   ['E', 'F']]) #two-dimensional array
array3 = np.array([['A', 'B', 'C'], 
                   ['D', 'E', 'F'], 
                   ['G', 'H', 'I']]) #two-dimensional array
print(array)
print(array.ndim) #this will print the number of dimensions of the array
print(array1)
print(array1.ndim) #this will print the number of dimensions of the array1
print(array2)
print(array2.ndim) #this will print the number of dimensions of the array2
print(array3)
print(array3.ndim) #this will print the number of dimensions of the array3


1
0
['A' 'B' 'C' 'D' 'E']
1
[['A' 'B']
 ['C' 'D']
 ['E' 'F']]
2
[['A' 'B' 'C']
 ['D' 'E' 'F']
 ['G' 'H' 'I']]
2


In [ ]:
#three dimensional arrays can be created using lists of lists of lists
array4 = np.array([[['A', 'B', 'C'], ['D', 'E', 'F']], 
                   [['G', 'H', 'I'], ['J', 'K', 'L']],
                   [['M', 'N', 'O'], ['P', 'Q', 'R']]]) #three-dimensional array
print(array4)
print(array4.ndim) #this will print the number of dimensions of the array4

# Need a consistent number of elements in each layer of sublists to create a multi-dimensional array. 
# If the sublists have different lengths, numpy will throw an error, which can be fixed with a placeholder
# array5 = np.array([['A', 'B', 'C'], ['D', 'E']]) #this will create an array of objects instead of a multi-dimensional array

array6 = np.array([
    [['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
    [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],
    [['S', 'T', 'U'], ['V', 'W', 'X'], ['Y', 'Z', '']]
])

# Shape is returned as (layers, rows, columns)
print(array6.shape)    # (3, 3, 3)

# Access each layer (2D array)
print(array6[0])       # First layer
print(array6[1])       # Second layer
print(array6[2])       # Third layer

# Using chained indexing, available for phyton too
print(array6[0][0][2])   # C 
print(array6[1][2][1])   # Q
print(array6[2][1][0])   # V

# Equivalent NumPy indexing
print(array6[0, 0, 2])   # C
print(array6[1, 2, 1])   # Q
print(array6[2, 1, 0])   # V

# String concatenation using elements from the array
word = array6[0, 0, 2] + array6[0, 0, 0] + array6[2, 0, 1]
print(word)              # CAT

[[['A' 'B' 'C']
  ['D' 'E' 'F']]

 [['G' 'H' 'I']
  ['J' 'K' 'L']]

 [['M' 'N' 'O']
  ['P' 'Q' 'R']]]
3
(3, 3, 3)
[['A' 'B' 'C']
 ['D' 'E' 'F']
 ['G' 'H' 'I']]
[['J' 'K' 'L']
 ['M' 'N' 'O']
 ['P' 'Q' 'R']]
[['S' 'T' 'U']
 ['V' 'W' 'X']
 ['Y' 'Z' '']]
C
Q
V
C
Q
V
CAT


In [ ]:
#slicing using array, can be row selection and column selection
array_index = np.array([[1, 2, 3, 4], 
                       [5, 6, 7, 8],
                       [9, 10, 11, 12], 
                       [13, 14, 15, 16]])

#array[start: end: step], ending index is exclusive
print(array_index[1]) #second row
print(array_index[-2]) #second to last row

print(array_index[0:3:2]) #skip row 1, so print row 0 and 2
print(array_index[::2]) #select all rows in array_index, but every second row only is printed
print(array_index[::-1]) #select all rows in array_index in reverse order, and all rows are printed

[5 6 7 8]
[ 9 10 11 12]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [49]:
#same with row indexing, column indexing also starts with 0, but with a , between row and column index
print(array_index[:, 0]) #select all rows, but only the first column
print(array_index[:,-2]) #select all rows, but only the second to last column

#slicing out range with : operator
print(array_index[:, 0:3]) #select all rows, but just the first three columns 

print(array_index[:, 1:]) #select all rows and starting from the second columns 

print(array_index[:, ::2]) #select all rows and columns, but get every second column only

print(array_index[1:2, ::-1]) #select second and third column, but go backward

[ 1  5  9 13]
[ 3  7 11 15]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]
[[8 7 6 5]]


In [4]:
my_list = [1,2,3,4,5]
print(my_list * 2) #this will not work because lists do not support vectorized operations
print(type(my_list)) #this will print <class 'list'>

my_array = np.array(my_list)
print(type(my_array)) #this will print <class 'numpy.ndarray'>
my_array * 2 #this will work because numpy arrays support vectorized operations
print(my_array * 2) #this will work because numpy arrays support vectorized operations

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
<class 'list'>
<class 'numpy.ndarray'>
[ 2  4  6  8 10]


In [ ]:
# Scalar arithmetic
array_numeric = np.array([1,2,3])
print(array_numeric + 2)
print(array_numeric - 3)
print(array_numeric / 4)
print(array_numeric ** 5)

[3 4 5]
[-2 -1  0]
[0.25 0.5  0.75]
[  1  32 243]


In [ ]:
# Vectorized math functions
array_vector = np.array([1,2,3,4])
print(np.sqrt(array_vector))
print(np.round(array_vector))
print(np.pi)

[1.         1.41421356 1.73205081 2.        ]
[1 2 3 4]
3.141592653589793


In [5]:
# Counting the circle with radius array
radii = np.array([1,2,3,4,5])
print(np.pi * radii ** 2)

for radius in radii:
    area = np.pi * radius ** 2
    print(f"With a radius of {radius}, the area is: {area: .2f}.")

[ 3.14159265 12.56637061 28.27433388 50.26548246 78.53981634]
With a radius of 1, the area is:  3.14.
With a radius of 2, the area is:  12.57.
With a radius of 3, the area is:  28.27.
With a radius of 4, the area is:  50.27.
With a radius of 5, the area is:  78.54.


In [6]:
# Element-wise arithmetic operations on NumPy arrays
array_element1 = np.array([4, 5, 6])
array_element2 = np.array([7, 8, 9])

# Addition
print(array_element1 + array_element2)   # [11 13 15]

# Subtraction
print(array_element1 - array_element2)   # [-3 -3 -3]

# Multiplication
print(array_element1 * array_element2)   # [28 40 54]

# Division
print(array_element1 / array_element2)   # [0.571... 0.625... 0.666...]

# Modulus
print(array_element2 % array_element1)

[11 13 15]
[-3 -3 -3]
[28 40 54]
[0.57142857 0.625      0.66666667]
[3 3 3]


In [ ]:
# Comparison operators
scores = np.array([91, 55, 100, 90, 83, 78])

# Student(s) who got a perfect score
print("Perfect score:", scores[scores == 100]) #[False, False, True, False, False]
print("Number of perfect scores:", np.sum(scores == 100))

# Students who passed (score > 70)
print("Passing scores:", scores[scores > 70]) #[False, False, True, False, False, False]
print("Number of passing students: ", np.sum(scores > 70))

# Conditional operator 
credits = np.where(scores >= 70, 3, 0)
print("Scores: ", scores)
print("Credits: ", credits)

Perfect score: [100]
Number of perfect scores: 1
Passing scores: [ 91 100  90  83  78]
Number of passing students:  5
Scores:  [ 91  55 100  90  83  78]
Credits:  [3 0 3 3 3 3]


In [24]:
import numpy as np

# Broadcasting allows NumPy to perform element-wise operations on arrays
# with different shapes without manually reshaping them.
#
# Two dimensions are compatible if:
# 1. They are the same size, or
# 2. One of them is 1.
#
# Compare array shapes from right to left.

array_broadcast1 = np.array([[1, 2, 3, 4]])   # Shape: (1, 4) -> 1 row, 4 columns
print(array_broadcast1.shape)

array_broadcast2 = np.array([[5], [6], [7], [8]])            # Shape: (4, 1) -> 4 rows, 1 column
print(array_broadcast2.shape)

print(array_broadcast1 * array_broadcast2)
# Shapes: (1, 4) and (4, 1)
# Compare dimensions from right to left, ensuring they meet either one of the compatibility rules: 
# - Columns: 4 and 1 -> compatible, result is 4
# - Rows:    1 and 4 -> compatible, result is 4
# The dimension with smaller size is expanded to match the larger dimension.
# The resulting shape: (4, 4)

(1, 4)
(4, 1)
[[ 5 10 15 20]
 [ 6 12 18 24]
 [ 7 14 21 28]
 [ 8 16 24 32]]


In [ ]:
array_broadcast3 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])  # Shape: (2, 4)

print(array_broadcast3)

array_broadcast4 = np.array([
    [5],
    [6],
    [7],
    [8]
])  # Shape: (4, 1)

print(array_broadcast4)

# This operation will raise a ValueError because the shapes are not compatible.
print(array_broadcast4 / array_broadcast3)

# Shapes: (4, 1) and (2, 4)
# Compare dimensions from right to left:
# - Columns: 1 and 4 -> Compatible (1 can be broadcast to 4)
# - Rows:    4 and 2 -> Not compatible (neither dimension is 1 and they are not equal)
# Result: ValueError - operands could not be broadcast together



[[1 2 3 4]
 [5 6 7 8]]
[[5]
 [6]
 [7]
 [8]]


ValueError: operands could not be broadcast together with shapes (4,1) (2,4) 

In [31]:

array_broadcast5 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])  # Shape: (4, 4)

print(array_broadcast5)

array_broadcast6 = np.array([
    [5],
    [6],
    [7],
    [8]
])  # Shape: (4, 1)

print(array_broadcast6)

print(array_broadcast6 / array_broadcast5)
# Shapes: (4, 4) and (2, 4)
# Compare dimensions from right to left:
# - Columns: 4 and 4 -> Compatible because the dimensions are equal
# - Rows:    4 and 2 -> Not compatible (neither dimension is 1 and they are not equal)
# The resulting shape: (4,4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[5]
 [6]
 [7]
 [8]]
[[5.         2.5        1.66666667 1.25      ]
 [1.2        1.         0.85714286 0.75      ]
 [0.77777778 0.7        0.63636364 0.58333333]
 [0.61538462 0.57142857 0.53333333 0.5       ]]


In [ ]:
# Use a Python list for general-purpose data storage.
# Use a NumPy array for numerical data and mathematical operations.
list_huruf = ['B', 'E', 'L', 'L']
list_huruf2 = ['A']
print(list_huruf + list_huruf2)


['B', 'E', 'L', 'L', 'A']


In [23]:
list_angka = [1, 2, 3, 4]
list_angka2 = [5]
print(list_angka + list_angka2)

[1, 2, 3, 4, 5]


In [18]:
array_hitung = np.array([1, 2, 3, 4])
array_hitung2 = np.array([5])
print(array_hitung % array_hitung2)

[1 2 3 4]


In [21]:
array_huruf = np.array(['B', 'E', 'L', 'L'])
array_huruf2 = np.array(['A'])
print(array_huruf + array_huruf2)

['BA' 'EA' 'LA' 'LA']


In [4]:
# Aggregate functions summarize data and produce a single value for analysis
array_aggregate = np.array([[1,2,3,4,5,6],
                            [7,8,9,10,11,12]])
print(np.sum(array_aggregate))
print(np.mean(array_aggregate))
print(np.min(array_aggregate))
print(np.max(array_aggregate))
print(np.std(array_aggregate))
print(np.argmin(array_aggregate))
print(np.argmax(array_aggregate))

78
6.5
1
12
3.452052529534663
0
11


In [ ]:
print(np.sum(array_aggregate,axis=0)) #summing all the columns so 1+7, 2+8, 3+9, 4+10, 5+11, 6+12
print(np.sum(array_aggregate, axis=1)) #summing all the rows so 1+2+3+4+5+6 and 7+8+9+10+11+12

[ 8 10 12 14 16 18]
[21 57]


In [ ]:
# Filtering refers to the process of selecting elements in an array
ages = np.array([
    [21, 14, 19, 20, 16, 18, 18, 25, 65],
    [16, 17, 18, 19, 25, 77, 28, 17, 21]
])

# Age groups
teenagers = ages[ages < 18]
young_adults = ages[(ages >= 18) & (ages <= 25)]
working_adults = ages[(ages >= 25) & (ages < 65)]
seniors= ages[ages >= 65]

print("Ages in the college classes:")
print(ages)

#Logical Operators: | OR, & AND, ~ NOT, ^ XOR
print(f"Teenagers (under 18): {teenagers}")
print(f"Young adults (18–25): {young_adults}")
print(f"Working adults (25-65): {working_adults}")
print(f"Seniors getting seniors discount (65+): {seniors}")

print()
# Find even ages
evens = ages[ages % 2 == 0]
print(f"People with even ages: {evens}")

# Find odd ages
odds = ages[ages % 2 != 0]
print(f"People with odd ages: {odds}")

# Keep adults (18+) and replace others with 0
adults = np.where(ages >= 18, ages, 0)
print(f"Adults (18+) only: {adults}") #fill value 0 to keep the shape of the array

print()
#Comparison operators
ages[ages == 18]     # Exactly 18
ages[ages != 18]     # Not 18
ages[ages > 20]      # Older than 20
ages[ages <= 17]     # 17 or younger


Ages in the college classes:
[[21 14 19 20 16 18 18 25 65]
 [16 17 18 19 25 77 28 17 21]]
Teenagers (under 18): [14 16 16 17 17]
Young adults (18–25): [21 19 20 18 18 25 18 19 25 21]
Working adults (25-65): [25 25 28]
Seniors getting seniors discount (65+): [65 77]

People with even ages: [14 20 16 18 18 16 18 28]
People with odd ages: [21 19 25 65 17 19 25 77 17 21]
Adults (18+) with minors replaced by 0: [[21  0 19 20  0 18 18 25 65]
 [ 0  0 18 19 25 77 28  0 21]]



array([14, 16, 16, 17, 17])

In [24]:
# Original prices
prices = np.array([100, 250, 80, 500])

# Find the indices where the price is at least 200
expensive = np.where(prices >= 200)
print(f"Positions of expensive items: {expensive}")
print(f"Prices of expensive items: {prices[expensive]}")

discounted = np.where(prices >= 200, prices * 0.9, prices)
print(f"Discounted expensive items are now priced: {discounted}")

Positions of expensive items: (array([1, 3]),)
Prices of expensive items: [250 500]
Discounted expensive items are now priced: [100. 225.  80. 450.]


In [5]:
#Random Number Generator
#Random numbers will be stored within an array
rng = np.random.default_rng()
print(rng.integers(low=1,high=101, size=3)) #high is exclusive
print(rng.integers(low=2, high=10, size=(3,2))) #the last parameter is for the dimension

[18 51 28]
[[3 5]
 [5 5]
 [7 8]]


In [8]:
# Random Number Generator
rng = np.random.default_rng(seed=2)

# Generate 5 random integers between 1 and 9
print(rng.integers(low=1, high=10, size=5))

# Generate one random floating-point number between 0 and 1
print(rng.uniform())

# Generate 4 random floating-point numbers between -1 and 1
print(rng.uniform(low=-1, high=1, size=4))

[8 3 1 3 4]
0.0919159421350969
[ 0.20020105  0.45712105 -0.62419785 -0.88970675]
